[package]
name = "chess-analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
nalgebra = "0.32.3"
pgn-reader = "0.25.0"
plotters = "0.3.5"
